name: Check typos

on:
  push:
    branches:
      - v*
      - main
      - master
      - release-v*
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Check spelling of file.txt
        uses: crate-ci/typos@master
